export { default as Home} from './Home'
export { default as Login} from './Login'
export { default as Register} from './Register'
export { default as PostPage} from './PostPage'
export { default as PostForm} from './PostForm'